name: Dev Environment (Build and Push docker image to azure container registry)
              
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to azure content registory
        uses: docker/login-action@v2
        with:
          registry: acrdev0101.azurecr.io
          username: acrDev0101
          password: XOF9Gby6tOSaWIGY/4wa5olsDCCy/6KfAaO9LHjaL/+ACRCqpTn/
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: acrDev0101/$(date +%s)

